name: golang
on:
  push:
    branches:
      - trunk
  pull_request:
env:
  GOTOOLCHAIN: local
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: oldstable
          cache-dependency-path: go.sum
      - name: test all
        run: go test -race ./...
